QUESTIONS = {
    1: {"title": "Print the Value of a Variable", "difficulty": "Very Easy",
        "code": "score = 95\nprint(score)", "tests": [""]},
    2: {"title": "Store and Print a String", "difficulty": "Very Easy",
        "code": 'greeting = "Hello"\nprint(greeting)', "tests": [""]},
    3: {"title": "Print a User-Provided Name", "difficulty": "Very Easy",
        "code": "name = input()\nprint(name)",
        "tests": ["Aman\n", "Zara\n", "Bob\n"]},
    4: {"title": "Swap Two Variables", "difficulty": "Easy",
        "code": "a = int(input())\nb = int(input())\na, b = b, a\nprint(a)\nprint(b)",
        "tests": ["3\n7\n", "1\n2\n", "-5\n9\n"]},
    5: {"title": "Multiple Assignment of Three Values", "difficulty": "Easy",
        "code": "x, y, z = 5, 10, 15\nprint(x + y + z)", "tests": [""]},
    6: {"title": "A Constant That Is Never Changed", "difficulty": "Easy",
        "code": "PI = 3.14159\nradius = int(input())\nprint(2 * PI * radius)",
        "tests": ["7\n", "1\n", "10\n"]},
    7: {"title": "Dynamic Typing: Change a Variable's Type", "difficulty": "Medium",
        "code": 'data = 10\ndata = "hello"\nprint(data)\nprint(type(data))',
        "tests": [""]},
    8: {"title": "Read Two Numbers Into Two Variables", "difficulty": "Easy",
        "code": "a = int(input())\nb = int(input())\nprint(a * b)",
        "tests": ["6\n9\n", "0\n5\n", "-4\n3\n"]},
    9: {"title": "Meaningful Variable Names", "difficulty": "Easy",
        "code": "distance = int(input())\ntime_hours = int(input())\nprint(distance / time_hours)",
        "tests": ["300\n5\n", "100\n4\n", "7\n2\n"]},
    10: {"title": "Invalid Identifier Awareness", "difficulty": "Easy",
        "code": 'my_var = "hello"\nprint(my_var)', "tests": [""]},
    11: {"title": "Sum Stored in a Variable", "difficulty": "Easy",
        "code": "a = int(input())\nb = int(input())\ntotal = a + b\nprint(total)",
        "tests": ["8\n12\n", "0\n0\n", "-3\n10\n"]},
    12: {"title": "Reuse a Variable to Accumulate", "difficulty": "Medium",
        "code": "total = 0\nfor _ in range(3):\n    total += int(input())\nprint(total)",
        "tests": ["1\n2\n3\n", "5\n5\n5\n", "10\n20\n30\n"]},
    13: {"title": "Case Sensitivity of Variables", "difficulty": "Medium",
        "code": "count = int(input())\nCount = count\nprint(count)\nprint(Count)",
        "tests": ["5\n", "0\n", "100\n"]},
    14: {"title": "Multiple Assignment from a Split", "difficulty": "Medium",
        "code": "a, b = map(int, input().split())\nprint(a + b)",
        "tests": ["4 9\n", "0 0\n", "-5 12\n"]},
    15: {"title": "Reassign With a New Value", "difficulty": "Easy",
        "code": "value = 5\nvalue = value * 3\nprint(value)", "tests": [""]},
    16: {"title": "Build a Sentence With Variables", "difficulty": "Easy",
        "code": 'name = input()\nage = int(input())\nprint(f"{name} is {age} years old.")',
        "tests": ["Aman\n25\n", "Bob\n1\n", "Zara\n40\n"]},
    17: {"title": "Variable Storing a Float Result", "difficulty": "Easy",
        "code": "a = int(input())\nb = int(input())\nresult = a / b\nprint(result)",
        "tests": ["10\n4\n", "1\n2\n", "20\n8\n"]},
    18: {"title": "Three Variables, Three Operations", "difficulty": "Medium",
        "code": "a = int(input())\nb = int(input())\nc = int(input())\ns = a + b\np = b * c\nd = c - a\nprint(s)\nprint(p)\nprint(d)",
        "tests": ["2\n3\n4\n", "1\n1\n1\n", "10\n5\n3\n"]},
    19: {"title": "Copying a Variable's Value", "difficulty": "Easy",
        "code": "a = 10\nb = a\na = 20\nprint(a)\nprint(b)", "tests": [""]},
    20: {"title": "A Descriptive Variable for a Constant Rate", "difficulty": "Easy",
        "code": "TAX_RATE = 0.05\namount = int(input())\ntax = amount * TAX_RATE\nprint(tax)",
        "tests": ["1000\n", "0\n", "250\n"]},
    21: {"title": "Store the Average", "difficulty": "Easy",
        "code": "a = int(input())\nb = int(input())\nc = int(input())\navg = (a + b + c) / 3\nprint(avg)",
        "tests": ["4\n6\n8\n", "0\n0\n0\n", "1\n2\n3\n"]},
    22: {"title": "Single Letter Variables", "difficulty": "Easy",
        "code": "x = int(input())\ny = int(input())\nprint(x + y)\nprint(x * y)",
        "tests": ["5\n7\n", "0\n0\n", "-3\n4\n"]},
    23: {"title": "Dynamic Reassignment to a Different Value", "difficulty": "Medium",
        "code": "n = int(input())\nn = n + 1\nn = n * 2\nprint(n)",
        "tests": ["5\n", "0\n", "10\n"]},
    24: {"title": "Store Results of Multiple Conversions", "difficulty": "Medium",
        "code": "km = int(input())\nmiles = km * 0.621371\nprint(miles)",
        "tests": ["10\n", "0\n", "100\n"]},
    25: {"title": "Combine Two Strings With a Variable", "difficulty": "Easy",
        "code": 'first = input()\nlast = input()\nfull = first + " " + last\nprint(full)',
        "tests": ["Ada\nLovelace\n", "A\nB\n", "John\nSmith\n"]},
    26: {"title": "Variable Holding a Boolean Result", "difficulty": "Easy",
        "code": "n = int(input())\nis_positive = n > 0\nprint(is_positive)",
        "tests": ["7\n", "-3\n", "0\n"]},
    27: {"title": "Swap Without Multiple Assignment", "difficulty": "Medium",
        "code": "a = int(input())\nb = int(input())\ntemp = a\na = b\nb = temp\nprint(a)\nprint(b)",
        "tests": ["1\n2\n", "5\n9\n", "-3\n7\n"]},
    28: {"title": "Variable Names With Underscores", "difficulty": "Easy",
        "code": "obtained_marks = int(input())\ntotal_marks = int(input())\nprint(obtained_marks / total_marks * 100)",
        "tests": ["42\n50\n", "10\n100\n", "0\n100\n"]},
    29: {"title": "Chain of Variables", "difficulty": "Medium",
        "code": "x = int(input())\ny = x + 2\nz = y * 3\nprint(z)",
        "tests": ["4\n", "0\n", "10\n"]},
    30: {"title": "Dynamic Typing Across Three Types", "difficulty": "Medium",
        "code": 'v = 1\nprint(v)\nv = "two"\nprint(v)\nv = 3.0\nprint(v)\nprint(type(v))',
        "tests": [""]},
}
