QUESTIONS = {
    1: {"title": "Print the Type of an Integer", "difficulty": "Very Easy",
        "code": "print(type(10))", "tests": [""]},
    2: {"title": "Print the Type of a Float", "difficulty": "Very Easy",
        "code": "print(type(3.14))", "tests": [""]},
    3: {"title": "Print the Type of a String", "difficulty": "Very Easy",
        "code": 'print(type("hello"))', "tests": [""]},
    4: {"title": "Print the Type of a Boolean", "difficulty": "Very Easy",
        "code": "print(type(True))", "tests": [""]},
    5: {"title": "Print the Value of None", "difficulty": "Very Easy",
        "code": "print(None)", "tests": [""]},
    6: {"title": "Convert a String to an Integer", "difficulty": "Very Easy",
        "code": "n = int(input())\nprint(n + 1)",
        "tests": ["5\n", "0\n", "-3\n"]},
    7: {"title": "Convert a String to a Float", "difficulty": "Very Easy",
        "code": "f = float(input())\nprint(f * 2)",
        "tests": ["2.5\n", "0.0\n", "1.25\n"]},
    8: {"title": "Convert an Integer to a String", "difficulty": "Easy",
        "code": "n = int(input())\ns = str(n)\nprint(s * 3)",
        "tests": ["7\n", "1\n", "123\n"]},
    9: {"title": "Convert a Number to a Boolean", "difficulty": "Medium",
        "code": "n = int(input())\nprint(bool(n))",
        "tests": ["0\n", "5\n", "-2\n"]},
    10: {"title": "Convert a String to a Boolean", "difficulty": "Medium",
        "code": "line = input()\nprint(bool(line))",
        "tests": ["\n", "hi\n", "0\n"]},
    11: {"title": "Type of an Arithmetic Result", "difficulty": "Easy",
        "code": "a = int(input())\nb = int(input())\nprint(type(a / b))\nprint(type(a + b))",
        "tests": ["4\n2\n", "10\n5\n", "1\n3\n"]},
    12: {"title": "Type Conversion in a Formula", "difficulty": "Easy",
        "code": "c = float(input())\nprint(c * 9 / 5 + 32)",
        "tests": ["100\n", "0\n", "-40\n"]},
    13: {"title": "Integer vs Float Division", "difficulty": "Easy",
        "code": "a = int(input())\nb = int(input())\nprint(a / b)\nprint(a // b)",
        "tests": ["17\n5\n", "10\n2\n", "1\n2\n"]},
    14: {"title": "The Type of None", "difficulty": "Very Easy",
        "code": "print(type(None))", "tests": [""]},
    15: {"title": "String to Int for Two Numbers", "difficulty": "Easy",
        "code": "a = int(input())\nb = int(input())\nprint(a + b)",
        "tests": ["12\n30\n", "0\n0\n", "-5\n5\n"]},
    16: {"title": "Float to Int (truncation)", "difficulty": "Medium",
        "code": "v = float(input())\nprint(v)\nprint(int(v))",
        "tests": ["7.9\n", "0.5\n", "3.1\n"]},
    17: {"title": "Check the Type of Input", "difficulty": "Easy",
        "code": "value = input()\nprint(type(value))",
        "tests": ["5\n", "hello\n", "1.5\n"]},
    18: {"title": "Bool of a Negative Number", "difficulty": "Easy",
        "code": "n = int(input())\nprint(bool(n))",
        "tests": ["-5\n", "0\n", "3\n"]},
    19: {"title": "Concatenate Strings After Conversion", "difficulty": "Medium",
        "code": 'n = int(input())\nprint("The number is " + str(n))',
        "tests": ["42\n", "0\n", "7\n"]},
    20: {"title": "Type of a Bool Expression", "difficulty": "Easy",
        "code": "a = int(input())\nb = int(input())\nprint(type(a > b))",
        "tests": ["3\n1\n", "1\n3\n", "5\n5\n"]},
    21: {"title": "Sum of Floats", "difficulty": "Easy",
        "code": "a = float(input())\nb = float(input())\nprint(a + b)",
        "tests": ["1.5\n2.25\n", "0.0\n0.0\n", "1.0\n2.0\n"]},
    22: {"title": "Distinguish 0 and 0.0 Types", "difficulty": "Medium",
        "code": "print(type(0))\nprint(type(0.0))", "tests": [""]},
    23: {"title": "Convert and Average", "difficulty": "Medium",
        "code": "a = float(input())\nb = float(input())\nc = float(input())\nprint((a + b + c) / 3)",
        "tests": ["1\n2\n3\n", "0\n0\n0\n", "10\n20\n30\n"]},
    24: {"title": "String Multiplication by an Int", "difficulty": "Easy",
        "code": "ch = input()\nn = int(input())\nprint(ch * n)",
        "tests": ["*\n5\n", "a\n3\n", "x\n1\n"]},
    25: {"title": "Type After Reassignment", "difficulty": "Medium",
        "code": "x = 5\nx = 5.0\nprint(type(x))", "tests": [""]},
    26: {"title": "int() of a Float-Looking String", "difficulty": "Medium",
        "code": "n = int(input())\nprint(n + 1)",
        "tests": ["7\n", "0\n", "100\n"]},
    27: {"title": "The Boolean of an Empty and Non-Empty String", "difficulty": "Easy",
        "code": 'print(bool(""))\nprint(bool("a"))', "tests": [""]},
    28: {"title": "Use str() in an f-string Alternative", "difficulty": "Medium",
        "code": 'n = int(input())\nprint("Value: " + str(n))',
        "tests": ["99\n", "0\n", "5\n"]},
    29: {"title": "Type of a Nested Conversion", "difficulty": "Medium",
        "code": 'print(type(int(float("3.7"))))', "tests": [""]},
    30: {"title": "Mixed Type Awareness", "difficulty": "Medium",
        "code": "v = float(input())\nn = int(v)\nprint(n)",
        "tests": ["9.99\n", "0.1\n", "5.0\n"]},
}
