QUESTIONS = {
    1: {"title": "Addition", "difficulty": "Very Easy",
        "code": "a = int(input())\nb = int(input())\nprint(a + b)",
        "tests": ["5\n7\n", "0\n0\n", "-3\n10\n"]},
    2: {"title": "Subtraction", "difficulty": "Very Easy",
        "code": "a = int(input())\nb = int(input())\nprint(a - b)",
        "tests": ["10\n3\n", "5\n5\n", "0\n7\n"]},
    3: {"title": "Multiplication", "difficulty": "Very Easy",
        "code": "a = int(input())\nb = int(input())\nprint(a * b)",
        "tests": ["6\n9\n", "0\n5\n", "-4\n3\n"]},
    4: {"title": "True Division", "difficulty": "Very Easy",
        "code": "a = int(input())\nb = int(input())\nprint(a / b)",
        "tests": ["10\n4\n", "7\n2\n", "1\n3\n"]},
    5: {"title": "Floor Division", "difficulty": "Very Easy",
        "code": "a = int(input())\nb = int(input())\nprint(a // b)",
        "tests": ["17\n5\n", "10\n3\n", "5\n5\n"]},
    6: {"title": "Modulo (Remainder)", "difficulty": "Very Easy",
        "code": "a = int(input())\nb = int(input())\nprint(a % b)",
        "tests": ["17\n5\n", "10\n10\n", "7\n3\n"]},
    7: {"title": "Exponentiation", "difficulty": "Very Easy",
        "code": "a = int(input())\nb = int(input())\nprint(a ** b)",
        "tests": ["2\n10\n", "5\n2\n", "1\n5\n"]},
    8: {"title": "Equality Comparison", "difficulty": "Very Easy",
        "code": "a = int(input())\nb = int(input())\nprint(a == b)",
        "tests": ["3\n3\n", "1\n2\n", "0\n0\n"]},
    9: {"title": "Greater Than", "difficulty": "Very Easy",
        "code": "a = int(input())\nb = int(input())\nprint(a > b)",
        "tests": ["7\n3\n", "3\n7\n", "5\n5\n"]},
    10: {"title": "Not Equal", "difficulty": "Very Easy",
        "code": "a = int(input())\nb = int(input())\nprint(a != b)",
        "tests": ["5\n5\n", "1\n2\n", "0\n0\n"]},
    11: {"title": "Logical AND", "difficulty": "Easy",
        "code": "a = int(input())\nb = int(input())\nprint((a > 0) and (b > 0))",
        "tests": ["3\n-2\n", "3\n2\n", "-1\n-1\n"]},
    12: {"title": "Logical OR", "difficulty": "Easy",
        "code": "a = int(input())\nb = int(input())\nprint((a > 0) or (b > 0))",
        "tests": ["-1\n4\n", "-1\n-1\n", "3\n2\n"]},
    13: {"title": "Logical NOT", "difficulty": "Easy",
        "code": "n = int(input())\nprint(not (n > 0))",
        "tests": ["5\n", "-5\n", "0\n"]},
    14: {"title": "Add and Assign (+=)", "difficulty": "Easy",
        "code": "a = int(input())\nb = int(input())\ntotal = a\ntotal += b\nprint(total)",
        "tests": ["5\n3\n", "0\n0\n", "-3\n7\n"]},
    15: {"title": "Multiply and Assign (*=)", "difficulty": "Easy",
        "code": "a = int(input())\nb = int(input())\np = a\np *= b\nprint(p)",
        "tests": ["4\n6\n", "5\n5\n", "0\n9\n"]},
    16: {"title": "Subtract and Assign (-=)", "difficulty": "Easy",
        "code": "n = int(input())\nv = 100\nv -= n\nprint(v)",
        "tests": ["25\n", "0\n", "100\n"]},
    17: {"title": "Divide and Assign (/=)", "difficulty": "Easy",
        "code": "n = int(input())\nx = 20\nx /= n\nprint(x)",
        "tests": ["4\n", "2\n", "5\n"]},
    18: {"title": "Membership `in` (string)", "difficulty": "Easy",
        "code": "sentence = input()\nletter = input()\nprint(letter in sentence)",
        "tests": ["hello\ne\n", "hello\nz\n", "python\np\n"]},
    19: {"title": "Membership `not in`", "difficulty": "Easy",
        "code": "word1 = input()\nword2 = input()\nprint(word1 not in word2)",
        "tests": ["cat\nconcatenate\n", "z\napple\n", "a\nbanana\n"]},
    20: {"title": "Identity `is` for None", "difficulty": "Medium",
        "code": "value = input()\nprint(value is None)",
        "tests": ["None\n", "hello\n", "None\n"]},
    21: {"title": "Identity `is not`", "difficulty": "Medium",
        "code": "value = input()\nprint(value is not None)",
        "tests": ["hello\n", "None\n", "x\n"]},
    22: {"title": "Order of Operations", "difficulty": "Medium",
        "code": "a = int(input())\nb = int(input())\nprint(a + b * 2)",
        "tests": ["3\n4\n", "0\n5\n", "-3\n2\n"]},
    23: {"title": "Chained Comparison", "difficulty": "Medium",
        "code": "a = int(input())\nb = int(input())\nc = int(input())\nprint(a < b < c)",
        "tests": ["1\n2\n3\n", "3\n2\n1\n", "1\n1\n2\n"]},
    24: {"title": "Combine Arithmetic and Comparison", "difficulty": "Medium",
        "code": "a = int(input())\nb = int(input())\nprint((a + b) > (a * b))",
        "tests": ["1\n2\n", "5\n5\n", "2\n3\n"]},
    25: {"title": "Logical Operators With Arithmetic", "difficulty": "Medium",
        "code": "n = int(input())\nprint((n % 2 == 0) and (n > 0))",
        "tests": ["6\n", "3\n", "-4\n", "0\n"]},
    26: {"title": "Use += to Accumulate a Sum", "difficulty": "Medium",
        "code": "total = 0\nfor _ in range(3):\n    total += int(input())\nprint(total)",
        "tests": ["1\n2\n3\n", "5\n5\n5\n", "10\n-2\n4\n"]},
    27: {"title": "`in` With a List", "difficulty": "Medium",
        "code": "lst = [int(x) for x in input().split()]\nvalue = int(input())\nprint(value in lst)",
        "tests": ["1 2 3\n2\n", "1 2 3\n9\n", "5 5\n5\n"]},
    28: {"title": "`is` With Integers", "difficulty": "Medium",
        "code": "n = int(input())\nprint(n is 10)",
        "tests": ["10\n", "5\n", "10\n"]},
    29: {"title": "Compound Comparison of Three Values", "difficulty": "Medium",
        "code": "a = int(input())\nb = int(input())\nc = int(input())\nprint(max(a, b, c) == c)",
        "tests": ["1\n2\n3\n", "3\n2\n1\n", "5\n5\n5\n"]},
    30: {"title": "Arithmetic With Assignment Operators", "difficulty": "Medium",
        "code": "n = int(input())\nx = 10\nx += n\nx *= 2\nx -= 5\nprint(x)",
        "tests": ["3\n", "0\n", "5\n"]},
}
