QUESTIONS = {
    1: {"title": "Read and Print a Line", "difficulty": "Very Easy",
        "code": "print(input())", "tests": ["Hello\n", "Python\n", "hi\n"]},
    2: {"title": "Print With a Custom Separator", "difficulty": "Easy",
        "code": 'print(1, 2, 3, sep="-")', "tests": [""]},
    3: {"title": "Print on One Line With a Custom End", "difficulty": "Easy",
        "code": 'print("a", end="")\nprint("b")', "tests": [""]},
    4: {"title": "Read Two Integers on One Line", "difficulty": "Easy",
        "code": "a, b = map(int, input().split())\nprint(a + b)",
        "tests": ["4 9\n", "0 0\n", "-5 12\n"]},
    5: {"title": "f-string With a Number", "difficulty": "Easy",
        "code": 'n = int(input())\nprint(f"You entered {n}.")',
        "tests": ["42\n", "0\n", "7\n"]},
    6: {"title": "Format a Float to Two Decimals", "difficulty": "Easy",
        "code": "v = float(input())\nprint(f\"{v:.2f}\")",
        "tests": ["3.14159\n", "2.5\n", "0.0\n"]},
    7: {"title": "Format an Integer in a Field Width", "difficulty": "Easy",
        "code": "n = int(input())\nprint(f\"{n:5d}\")",
        "tests": ["7\n", "123\n", "0\n"]},
    8: {"title": "Combine Two Inputs in One Line", "difficulty": "Easy",
        "code": 'name = input()\nage = int(input())\nprint(f"{name} is {age} years old.")',
        "tests": ["Aman\n25\n", "Bob\n1\n", "Zara\n40\n"]},
    9: {"title": "Print an Arithmetic Result", "difficulty": "Easy",
        "code": "a = int(input())\nb = int(input())\nprint(f\"Sum: {a + b}\")",
        "tests": ["3\n4\n", "0\n0\n", "-5\n9\n"]},
    10: {"title": "Multiple print() Calls Stack Lines", "difficulty": "Very Easy",
        "code": 'print("line1")\nprint("line2")\nprint("line3")', "tests": [""]},
    11: {"title": "Read Three Values on One Line", "difficulty": "Medium",
        "code": "a, b, c = map(int, input().split())\nprint((a + b + c) / 3)",
        "tests": ["1 2 3\n", "4 4 4\n", "10 20 30\n"]},
    12: {"title": "f-string With Expressions Inside Braces", "difficulty": "Easy",
        "code": 'n = int(input())\nprint(f"Double: {n * 2}")',
        "tests": ["5\n", "0\n", "10\n"]},
    13: {"title": "Format a Percentage", "difficulty": "Medium",
        "code": 'obtained = int(input())\ntotal = int(input())\nprint(f"{(obtained / total) * 100:.1f}%")',
        "tests": ["42\n50\n", "10\n100\n", "30\n40\n"]},
    14: {"title": "Print a List", "difficulty": "Easy",
        "code": "lst = [int(x) for x in input().split()]\nprint(lst)",
        "tests": ["1 2 3\n", "5\n", "1 1 1\n"]},
    15: {"title": "Read a Character and Repeat", "difficulty": "Easy",
        "code": "ch = input()\nn = int(input())\nprint(ch * n)",
        "tests": ["*\n5\n", "a\n3\n", "x\n1\n"]},
    16: {"title": "Multiple Inputs With a Loop", "difficulty": "Medium",
        "code": "n = int(input())\ntotal = 0\nfor _ in range(n):\n    total += int(input())\nprint(total)",
        "tests": ["3\n1\n2\n3\n", "1\n5\n", "2\n-3\n4\n"]},
    17: {"title": "Print With Padding on Both Sides", "difficulty": "Medium",
        "code": 'word = input()\nprint(f"{word:^10}")',
        "tests": ["hi\n", "hello\n", "a\n"]},
    18: {"title": "f-string With Multiple Values", "difficulty": "Easy",
        "code": "a = int(input())\nb = int(input())\nc = int(input())\nprint(f\"a={a} b={b} c={c}\")",
        "tests": ["1\n2\n3\n", "0\n0\n0\n", "5\n5\n5\n"]},
    19: {"title": "Left-Align a String in a Field", "difficulty": "Medium",
        "code": 'word = input()\nprint(f"{word:<8}!")',
        "tests": ["hi\n", "hello\n", "abcdefghij\n"]},
    20: {"title": "Print the Type of Input", "difficulty": "Easy",
        "code": "value = input()\nprint(f\"Type: {type(value)}\")",
        "tests": ["5\n", "hello\n", "1.5\n"]},
    21: {"title": "Format With Thousand Separators", "difficulty": "Medium",
        "code": "n = int(input())\nprint(f\"{n:,}\")",
        "tests": ["1000000\n", "1234567\n", "999\n"]},
    22: {"title": "Read and Split Into Words", "difficulty": "Medium",
        "code": "print(len(input().split()))",
        "tests": ["Hello world of Python\n", "hi\n", "a b c\n"]},
    23: {"title": "Print Multiple Results on Separate Lines", "difficulty": "Medium",
        "code": "a = int(input())\nb = int(input())\nprint(a + b)\nprint(a - b)\nprint(a * b)",
        "tests": ["6\n3\n", "0\n0\n", "-5\n2\n"]},
    24: {"title": "f-string With a Float Field Width", "difficulty": "Medium",
        "code": "v = float(input())\nprint(f\"{v:8.2f}\")",
        "tests": ["5.5\n", "1.0\n", "100.25\n"]},
    25: {"title": "Escape a Curly Brace in an f-string", "difficulty": "Medium",
        "code": 'print(f"The set has {{3}} items")', "tests": [""]},
    26: {"title": "Read a Value and Echo With Labels", "difficulty": "Easy",
        "code": 'name = input()\nprint(f"Hello {name}!")',
        "tests": ["Zara\n", "Aman\n", "Bob\n"]},
    27: {"title": "Print a Table Row", "difficulty": "Medium",
        "code": 'item = input()\nqty = int(input())\nprice = float(input())\nprint(f"{item:<10}{qty:>4}{price:>8.2f}")',
        "tests": ["Apple\n3\n2.5\n", "Pen\n1\n10.0\n", "Book\n5\n3.25\n"]},
    28: {"title": "Read Two Numbers on the Same Line and Print Sum", "difficulty": "Easy",
        "code": "a, b = map(int, input().split())\nprint(a + b)",
        "tests": ["8 12\n", "0 0\n", "-4 9\n"]},
    29: {"title": "Format With a Plus Sign for Positives", "difficulty": "Medium",
        "code": "n = int(input())\nprint(f\"{n:+d}\")",
        "tests": ["5\n", "-5\n", "0\n"]},
    30: {"title": "Build a Multi-Line Output", "difficulty": "Medium",
        "code": "values = [int(input()) for _ in range(3)]\nprint(*values, sep=\" | \")",
        "tests": ["1\n2\n3\n", "5\n5\n5\n", "10\n20\n30\n"]},
}
