QUESTIONS = {
    1: {"title": "Basic if", "difficulty": "Very Easy",
        "code": "n = int(input())\nif n > 0:\n    print(\"Positive\")\nelse:\n    print(\"Non-positive\")",
        "tests": ["5\n", "-3\n", "0\n"]},
    2: {"title": "if/else Parity", "difficulty": "Very Easy",
        "code": "n = int(input())\nif n % 2 == 0:\n    print(\"Even\")\nelse:\n    print(\"Odd\")",
        "tests": ["8\n", "7\n", "0\n"]},
    3: {"title": "if/elif/else Grade", "difficulty": "Easy",
        "code": "n = int(input())\nif n >= 80:\n    print(\"High\")\nelif n >= 50:\n    print(\"Mid\")\nelse:\n    print(\"Low\")",
        "tests": ["75\n", "90\n", "30\n"]},
    4: {"title": "Nested if", "difficulty": "Medium",
        "code": "a = int(input())\nb = int(input())\nif a > 0:\n    if b > 0:\n        print(\"Both positive\")\n    else:\n        print(\"Only a positive\")\nelse:\n    print(\"Not a positive\")",
        "tests": ["3\n2\n", "3\n-2\n", "-1\n2\n"]},
    5: {"title": "Multiple Conditions With and", "difficulty": "Easy",
        "code": "n = int(input())\nif n >= 10 and n <= 20:\n    print(\"Yes\")\nelse:\n    print(\"No\")",
        "tests": ["15\n", "5\n", "20\n", "21\n"]},
    6: {"title": "Ternary Expression", "difficulty": "Easy",
        "code": 'n = int(input())\nresult = "even" if n % 2 == 0 else "odd"\nprint(result)',
        "tests": ["4\n", "3\n", "0\n"]},
    7: {"title": "Ternary for Larger of Two", "difficulty": "Easy",
        "code": "a = int(input())\nb = int(input())\nlarger = a if a > b else b\nprint(larger)",
        "tests": ["7\n3\n", "3\n7\n", "5\n5\n"]},
    8: {"title": "Leap Year (multiple conditions)", "difficulty": "Medium",
        "code": "year = int(input())\nif year % 400 == 0 or (year % 4 == 0 and year % 100 != 0):\n    print(\"Leap\")\nelse:\n    print(\"Not leap\")",
        "tests": ["2024\n", "2000\n", "1900\n", "2021\n"]},
    9: {"title": "if/elif Chain for Signs", "difficulty": "Easy",
        "code": "n = int(input())\nif n > 0:\n    print(\"Positive\")\nelif n < 0:\n    print(\"Negative\")\nelse:\n    print(\"Zero\")",
        "tests": ["-3\n", "0\n", "5\n"]},
    10: {"title": "Nested Ternary", "difficulty": "Medium",
        "code": 'n = int(input())\nprint("Positive" if n > 0 else ("Zero" if n == 0 else "Negative"))',
        "tests": ["0\n", "5\n", "-5\n"]},
    11: {"title": "Comparison Chain", "difficulty": "Easy",
        "code": "a = int(input())\nb = int(input())\nc = int(input())\nif a < b < c:\n    print(\"Yes\")\nelse:\n    print(\"No\")",
        "tests": ["1\n2\n3\n", "3\n2\n1\n", "1\n1\n2\n"]},
    12: {"title": "Multiple Conditions With or", "difficulty": "Easy",
        "code": "n = int(input())\nif n % 3 == 0 or n % 5 == 0:\n    print(\"Yes\")\nelse:\n    print(\"No\")",
        "tests": ["9\n", "5\n", "7\n", "15\n"]},
    13: {"title": "Nested if/else for Max of Three", "difficulty": "Medium",
        "code": "a = int(input())\nb = int(input())\nc = int(input())\nif a >= b and a >= c:\n    print(a)\nelif b >= c:\n    print(b)\nelse:\n    print(c)",
        "tests": ["3\n7\n5\n", "9\n1\n4\n", "1\n2\n3\n"]},
    14: {"title": "Ternary to Choose a String", "difficulty": "Easy",
        "code": 'score = int(input())\nprint("Pass" if score >= 40 else "Fail")',
        "tests": ["55\n", "30\n", "40\n"]},
    15: {"title": "if/elif/else for Temperature Category", "difficulty": "Medium",
        "code": "t = int(input())\nif t >= 30:\n    print(\"Hot\")\nelif t >= 20:\n    print(\"Warm\")\nelif t >= 10:\n    print(\"Cool\")\nelse:\n    print(\"Cold\")",
        "tests": ["25\n", "35\n", "15\n", "5\n"]},
    16: {"title": "Nested Conditions for a Rectangle", "difficulty": "Medium",
        "code": "a = int(input())\nb = int(input())\nif a > 0 and b > 0:\n    print(f\"Area {a * b}\")\nelse:\n    print(\"Invalid\")",
        "tests": ["4\n5\n", "-2\n5\n", "3\n3\n"]},
    17: {"title": "Ternary Inside a String", "difficulty": "Easy",
        "code": 'n = int(input())\nprint(f"It is {n} {\'even\' if n % 2 == 0 else \'odd\'}.")',
        "tests": ["3\n", "4\n", "0\n"]},
    18: {"title": "Multiple Conditions With not", "difficulty": "Medium",
        "code": "n = int(input())\nif not (1 <= n <= 5):\n    print(\"Yes\")\nelse:\n    print(\"No\")",
        "tests": ["9\n", "3\n", "1\n", "6\n"]},
    19: {"title": "if/elif for Number of Digits", "difficulty": "Medium",
        "code": "n = int(input())\nd = len(str(n))\nif d == 1:\n    print(\"One digit\")\nelif d == 2:\n    print(\"Two digits\")\nelse:\n    print(\"Many digits\")",
        "tests": ["99\n", "7\n", "123\n", "1000\n"]},
    20: {"title": "Ternary to Return Absolute Value", "difficulty": "Medium",
        "code": "n = int(input())\nprint(n if n >= 0 else -n)",
        "tests": ["-7\n", "0\n", "7\n"]},
    21: {"title": "Nested if/elif for a Menu Choice", "difficulty": "Medium",
        "code": "c = input()\nif c == \"a\":\n    print(\"Add\")\nelif c == \"s\":\n    print(\"Subtract\")\nelif c == \"m\":\n    print(\"Multiply\")\nelse:\n    print(\"Unknown\")",
        "tests": ["a\n", "s\n", "m\n", "x\n"]},
    22: {"title": "Multiple Conditions With and/or Combined", "difficulty": "Medium",
        "code": "n = int(input())\nif (n > 0 and n % 2 == 0) or (n < 0 and n % 2 != 0):\n    print(\"Yes\")\nelse:\n    print(\"No\")",
        "tests": ["6\n", "-5\n", "5\n", "-6\n"]},
    23: {"title": "Ternary With a Computation", "difficulty": "Medium",
        "code": "a = int(input())\nb = int(input())\nresult = a + b if a > b else a * b\nprint(result)",
        "tests": ["3\n5\n", "5\n3\n", "4\n4\n"]},
    24: {"title": "if/elif/else for a Triangle Sides Check", "difficulty": "Hard",
        "code": "a = int(input())\nb = int(input())\nc = int(input())\nif a < b + c and b < a + c and c < a + b:\n    print(\"Valid\")\nelse:\n    print(\"Invalid\")",
        "tests": ["3\n4\n5\n", "1\n2\n10\n", "5\n5\n5\n"]},
    25: {"title": "Nested Ternary for Three Categories", "difficulty": "Medium",
        "code": 'n = int(input())\nprint("Excellent" if n >= 90 else ("Good" if n >= 60 else "Needs work"))',
        "tests": ["85\n", "95\n", "30\n"]},
    26: {"title": "if to Guard Division by Zero", "difficulty": "Medium",
        "code": "a = int(input())\nb = int(input())\nif b == 0:\n    print(\"Cannot divide\")\nelse:\n    print(a / b)",
        "tests": ["5\n0\n", "5\n2\n", "10\n4\n"]},
    27: {"title": "Multiple Conditions to Classify a Number", "difficulty": "Hard",
        "code": "n = int(input())\nif n % 2 == 0 and n % 3 == 0 and n % 5 == 0:\n    print(\"Special\")\nelse:\n    print(\"Normal\")",
        "tests": ["30\n", "6\n", "15\n", "60\n"]},
    28: {"title": "Ternary in a Comparison Loop Setting", "difficulty": "Medium",
        "code": "a = int(input())\nb = int(input())\nif a > b:\n    print(\"First\")\nelif b > a:\n    print(\"Second\")\nelse:\n    print(\"Equal\")",
        "tests": ["7\n7\n", "7\n3\n", "3\n7\n"]},
    29: {"title": "Nested if/else for a Login-Style Check", "difficulty": "Medium",
        "code": 'user = input()\npassword = input()\nif user == "admin":\n    if password == "1234":\n        print("Welcome")\n    else:\n        print("Wrong password")\nelse:\n    print("Unknown user")',
        "tests": ["admin\n1234\n", "admin\n9999\n", "bob\n1234\n"]},
    30: {"title": "Ternary With Logical Operators", "difficulty": "Hard",
        "code": "a = int(input())\nb = int(input())\nc = int(input())\nprint(a if a >= b and a >= c else (b if b >= c else c))",
        "tests": ["1\n9\n4\n", "9\n1\n4\n", "1\n4\n9\n"]},
}
