QUESTIONS = {
    1: {"title": "for Loop Over a Range", "difficulty": "Very Easy",
        "code": "n = int(input())\nfor i in range(1, n + 1):\n    print(i)",
        "tests": ["3\n", "1\n", "5\n"]},
    2: {"title": "while Loop Countdown", "difficulty": "Very Easy",
        "code": "n = int(input())\nwhile n >= 1:\n    print(n)\n    n -= 1",
        "tests": ["3\n", "1\n", "5\n"]},
    3: {"title": "Sum With a for Loop", "difficulty": "Easy",
        "code": "n = int(input())\ntotal = 0\nfor i in range(1, n + 1):\n    total += i\nprint(total)",
        "tests": ["5\n", "1\n", "100\n"]},
    4: {"title": "Sum With a while Loop", "difficulty": "Easy",
        "code": "n = int(input())\ntotal = 0\ni = 1\nwhile i <= n:\n    total += i\n    i += 1\nprint(total)",
        "tests": ["4\n", "1\n", "10\n"]},
    5: {"title": "range() With a Step", "difficulty": "Easy",
        "code": "n = int(input())\nfor i in range(2, n + 1, 2):\n    print(i)",
        "tests": ["8\n", "2\n", "10\n"]},
    6: {"title": "break to Stop Early", "difficulty": "Medium",
        "code": "n = int(input())\nfor i in range(1, n + 1):\n    print(i)\n    if i % 7 == 0:\n        break",
        "tests": ["10\n", "7\n", "20\n"]},
    7: {"title": "continue to Skip", "difficulty": "Medium",
        "code": "n = int(input())\nfor i in range(1, n + 1):\n    if i % 3 == 0:\n        continue\n    print(i)",
        "tests": ["6\n", "1\n", "10\n"]},
    8: {"title": "pass as a Placeholder", "difficulty": "Easy",
        "code": "n = int(input())\nfor i in range(1, n + 1):\n    if i == 5:\n        pass\n    else:\n        print(i)",
        "tests": ["7\n", "5\n", "10\n"]},
    9: {"title": "First N Even Numbers", "difficulty": "Easy",
        "code": "n = int(input())\nfor i in range(1, n + 1):\n    print(i * 2)",
        "tests": ["4\n", "1\n", "6\n"]},
    10: {"title": "while Loop That Runs a Fixed Number of Times", "difficulty": "Medium",
        "code": "n = int(input())\ni = 1\nwhile i <= n:\n    print(f\"Iteration {i}\")\n    i += 1",
        "tests": ["2\n", "1\n", "3\n"]},
    11: {"title": "Product With a for Loop (Factorial)", "difficulty": "Easy",
        "code": "n = int(input())\np = 1\nfor i in range(1, n + 1):\n    p *= i\nprint(p)",
        "tests": ["5\n", "0\n", "10\n"]},
    12: {"title": "Sum of Even Numbers 1..n", "difficulty": "Easy",
        "code": "n = int(input())\ntotal = 0\nfor i in range(1, n + 1):\n    if i % 2 == 0:\n        total += i\nprint(total)",
        "tests": ["10\n", "1\n", "5\n"]},
    13: {"title": "Count Odd Numbers 1..n", "difficulty": "Easy",
        "code": "n = int(input())\ncount = 0\nfor i in range(1, n + 1):\n    if i % 2 != 0:\n        count += 1\nprint(count)",
        "tests": ["9\n", "1\n", "10\n"]},
    14: {"title": "Nested Loop: Square of Asterisks", "difficulty": "Medium",
        "code": "n = int(input())\nfor _ in range(n):\n    print(\"*\" * n)",
        "tests": ["3\n", "1\n", "5\n"]},
    15: {"title": "Nested Loop: Triangle of Numbers", "difficulty": "Medium",
        "code": "n = int(input())\nfor row in range(1, n + 1):\n    print(\" \".join(str(c) for c in range(1, row + 1)))",
        "tests": ["3\n", "1\n", "4\n"]},
    16: {"title": "Multiplication Table", "difficulty": "Easy",
        "code": "n = int(input())\nfor i in range(1, 11):\n    print(f\"{n} x {i} = {n * i}\")",
        "tests": ["3\n", "1\n", "7\n"]},
    17: {"title": "Sum of Digits With a while Loop", "difficulty": "Medium",
        "code": "n = int(input())\ntotal = 0\nwhile n > 0:\n    total += n % 10\n    n //= 10\nprint(total)",
        "tests": ["123\n", "7\n", "12345\n"]},
    18: {"title": "Count Digits", "difficulty": "Medium",
        "code": "n = int(input())\ncount = 0\nwhile n > 0:\n    n //= 10\n    count += 1\nprint(count)",
        "tests": ["78654\n", "7\n", "1\n"]},
    19: {"title": "Reverse a Number", "difficulty": "Medium",
        "code": "n = int(input())\nrev = 0\nwhile n > 0:\n    rev = rev * 10 + (n % 10)\n    n //= 10\nprint(rev)",
        "tests": ["4321\n", "7\n", "12345\n"]},
    20: {"title": "Sum of a Range a..b", "difficulty": "Easy",
        "code": "a = int(input())\nb = int(input())\nprint(sum(range(a, b + 1)))",
        "tests": ["4\n7\n", "1\n1\n", "1\n5\n"]},
    21: {"title": "First N Fibonacci Numbers", "difficulty": "Medium",
        "code": "n = int(input())\na, b = 0, 1\nfor _ in range(n):\n    print(a)\n    a, b = b, a + b",
        "tests": ["5\n", "1\n", "8\n"]},
    22: {"title": "while Loop Until a Condition", "difficulty": "Medium",
        "code": "n = int(input())\nwhile n > 0:\n    print(n)\n    n //= 2",
        "tests": ["8\n", "1\n", "10\n"]},
    23: {"title": "break in a Nested Loop", "difficulty": "Hard",
        "code": "n = int(input())\ntotal_stars = 0\nfor row in range(1, n + 1):\n    line = \"\"\n    for _ in range(row):\n        line += \"*\"\n        total_stars += 1\n    print(line)\n    if total_stars >= n:\n        break",
        "tests": ["3\n", "1\n", "5\n"]},
    24: {"title": "Nested Loop: Multiplication Triangle", "difficulty": "Medium",
        "code": "n = int(input())\nfor i in range(1, n + 1):\n    print(\" \".join(str(i * j) for j in range(1, i + 1)))",
        "tests": ["3\n", "1\n", "4\n"]},
    25: {"title": "Sum of Squares", "difficulty": "Easy",
        "code": "n = int(input())\ntotal = 0\nfor i in range(1, n + 1):\n    total += i ** 2\nprint(total)",
        "tests": ["3\n", "1\n", "5\n"]},
    26: {"title": "Print Numbers Divisible by 3 or 5", "difficulty": "Easy",
        "code": "n = int(input())\nfor i in range(1, n + 1):\n    if i % 3 == 0 or i % 5 == 0:\n        print(i)",
        "tests": ["10\n", "15\n", "5\n"]},
    27: {"title": "while Loop With continue and break", "difficulty": "Hard",
        "code": "x = 1\ncount = 0\nwhile count < 5:\n    if x % 3 == 0:\n        x += 1\n        continue\n    print(x)\n    count += 1\n    x += 1",
        "tests": [""]},
    28: {"title": "Nested Loop: Hollow Square", "difficulty": "Hard",
        "code": "n = int(input())\nfor r in range(n):\n    line = \"\"\n    for c in range(n):\n        if r == 0 or r == n - 1 or c == 0 or c == n - 1:\n            line += \"*\"\n        else:\n            line += \" \"\n    print(line)",
        "tests": ["4\n", "3\n", "5\n"]},
    29: {"title": "Sum of First N Odd Numbers", "difficulty": "Easy",
        "code": "n = int(input())\ntotal = 0\nfor i in range(1, n + 1):\n    total += 2 * i - 1\nprint(total)",
        "tests": ["3\n", "1\n", "5\n"]},
    30: {"title": "Largest Digit Using a Loop", "difficulty": "Medium",
        "code": "n = int(input())\nmx = 0\nwhile n > 0:\n    if n % 10 > mx:\n        mx = n % 10\n    n //= 10\nprint(mx)",
        "tests": ["78219\n", "1\n", "999\n"]},
}
