QUESTIONS = {
    1: {"title": "String Length", "difficulty": "Very Easy",
        "code": "s = input()\nprint(len(s))",
        "tests": ["hello\n", "a\n", "python\n"]},
    2: {"title": "First Character", "difficulty": "Very Easy",
        "code": "s = input()\nprint(s[0])",
        "tests": ["Python\n", "a\n", "hello\n"]},
    3: {"title": "Last Character", "difficulty": "Very Easy",
        "code": "s = input()\nprint(s[-1])",
        "tests": ["Python\n", "a\n", "hello\n"]},
    4: {"title": "Uppercase", "difficulty": "Very Easy",
        "code": "s = input()\nprint(s.upper())",
        "tests": ["hello\n", "AbC\n", "WORLD\n"]},
    5: {"title": "Lowercase", "difficulty": "Very Easy",
        "code": "s = input()\nprint(s.lower())",
        "tests": ["WORLD\n", "AbC\n", "hello\n"]},
    6: {"title": "Strip Whitespace", "difficulty": "Easy",
        "code": "s = input()\nprint(s.strip())",
        "tests": ["  hi  \n", "hello\n", "  a\n"]},
    7: {"title": "Replace a Character", "difficulty": "Easy",
        "code": "s = input()\nch = input()\nprint(s.replace(\" \", ch))",
        "tests": ["a b c\n-\n", "hello world\n_\n", "no spaces\nx\n"]},
    8: {"title": "Split a String", "difficulty": "Easy",
        "code": "s = input()\nprint(s.split())",
        "tests": ["hello world\n", "hi\n", "a b c\n"]},
    9: {"title": "Join a List of Words", "difficulty": "Easy",
        "code": "words = input().split()\nprint(\" - \".join(words))",
        "tests": ["a b c\n", "hi\n", "x y\n"]},
    10: {"title": "Slice First Three Characters", "difficulty": "Easy",
        "code": "s = input()\nprint(s[:3])",
        "tests": ["Python\n", "abcdef\n", "xyz\n"]},
    11: {"title": "Slice Last Three Characters", "difficulty": "Easy",
        "code": "s = input()\nprint(s[-3:])",
        "tests": ["Python\n", "abcdef\n", "xyz\n"]},
    12: {"title": "Reverse a String", "difficulty": "Easy",
        "code": "s = input()\nprint(s[::-1])",
        "tests": ["hello\n", "a\n", "python\n"]},
    13: {"title": "Remove First and Last Characters", "difficulty": "Easy",
        "code": "s = input()\nprint(s[1:-1])",
        "tests": ["hello\n", "abcd\n", "python\n"]},
    14: {"title": "Check Palindrome", "difficulty": "Medium",
        "code": "s = input()\nif s == s[::-1]:\n    print(\"Palindrome\")\nelse:\n    print(\"Not palindrome\")",
        "tests": ["madam\n", "hello\n", "a\n", "racecar\n"]},
    15: {"title": "Count a Character", "difficulty": "Easy",
        "code": "s = input()\nch = input()\nprint(s.count(ch))",
        "tests": ["banana\na\n", "hello\nl\n", "python\nz\n"]},
    16: {"title": "Middle Character(s)", "difficulty": "Medium",
        "code": "s = input()\nn = len(s)\nif n % 2 == 1:\n    print(s[n // 2])\nelse:\n    print(s[n // 2 - 1 : n // 2 + 1])",
        "tests": ["hello\n", "abcd\n", "a\n"]},
    17: {"title": "Every Other Character", "difficulty": "Easy",
        "code": "s = input()\nprint(s[::2])",
        "tests": ["abcdef\n", "hello\n", "a\n"]},
    18: {"title": "Replace a Word", "difficulty": "Medium",
        "code": "s = input()\nw1 = input()\nw2 = input()\nprint(s.replace(w1, w2))",
        "tests": ["I like apples\napples\nmangoes\n", "hello hello\nhello\nbye\n", "a b\na\nx\n"]},
    19: {"title": "Count Words", "difficulty": "Easy",
        "code": "s = input()\nprint(len(s.split()))",
        "tests": ["Hello world of Python\n", "hi\n", "a b c\n"]},
    20: {"title": "Uppercase First Letter of Each Word", "difficulty": "Medium",
        "code": "s = input()\nprint(\" \".join(w[0].upper() + w[1:] for w in s.split()))",
        "tests": ["the quick brown fox\n", "hello\n", "a b c\n"]},
    21: {"title": "Reverse Each Word", "difficulty": "Medium",
        "code": "s = input()\nprint(\" \".join(w[::-1] for w in s.split()))",
        "tests": ["hello world\n", "python\n", "a b c\n"]},
    22: {"title": "First Letter of Each Word", "difficulty": "Medium",
        "code": "s = input()\nprint(\"\".join(w[0] for w in s.split()))",
        "tests": ["Hello World Of Python\n", "a b c\n", "hi\n"]},
    23: {"title": "Check if Starts and Ends With Same Character", "difficulty": "Easy",
        "code": "s = input()\nif s[0] == s[-1]:\n    print(\"Yes\")\nelse:\n    print(\"No\")",
        "tests": ["madam\n", "hello\n", "a\n"]},
    24: {"title": "Count Vowels", "difficulty": "Medium",
        "code": "s = input().lower()\nprint(sum(1 for c in s if c in \"aeiou\"))",
        "tests": ["Hello\n", "python\n", "AEIOU\n"]},
    25: {"title": "Split on a Specific Character", "difficulty": "Medium",
        "code": "s = input()\nprint(s.split(\",\"))",
        "tests": ["apple,banana\n", "a,b,c\n", "one\n"]},
    26: {"title": "Strip and Uppercase", "difficulty": "Easy",
        "code": "s = input()\nprint(s.strip().upper())",
        "tests": ["  hi  \n", "hello\n", " a \n"]},
    27: {"title": "Extract Digits", "difficulty": "Medium",
        "code": "s = input()\nprint(\"\".join(c for c in s if c.isdigit()))",
        "tests": ["a1b2c3\n", "hello\n", "12345\n"]},
    28: {"title": "Remove Vowels", "difficulty": "Medium",
        "code": "s = input()\nprint(\"\".join(c for c in s if c.lower() not in \"aeiou\"))",
        "tests": ["hello\n", "python\n", "AEIOU\n"]},
    29: {"title": "Word Lengths", "difficulty": "Medium",
        "code": "s = input()\nfor w in s.split():\n    print(f\"{w}: {len(w)}\")",
        "tests": ["hi there\n", "hello\n", "a bb ccc\n"]},
    30: {"title": "Reverse the Order of Words", "difficulty": "Medium",
        "code": "s = input()\nprint(\" \".join(s.split()[::-1]))",
        "tests": ["I love Python\n", "hi\n", "a b c\n"]},
}
