QUESTIONS = {
    1: {"title": "Create a List Literal", "difficulty": "Very Easy",
        "code": "lst = [10, 20, 30]\nprint(lst)", "tests": [""]},
    2: {"title": "Length of a List", "difficulty": "Very Easy",
        "code": "lst = input().split()\nprint(len(lst))",
        "tests": ["1 2 3 4\n", "5\n", "1 1 1\n"]},
    3: {"title": "First Element", "difficulty": "Very Easy",
        "code": "lst = input().split()\nprint(lst[0])",
        "tests": ["5 8 3\n", "1\n", "9 7\n"]},
    4: {"title": "Last Element", "difficulty": "Very Easy",
        "code": "lst = input().split()\nprint(lst[-1])",
        "tests": ["5 8 3\n", "1\n", "9 7\n"]},
    5: {"title": "Sum of a List", "difficulty": "Easy",
        "code": "lst = [int(x) for x in input().split()]\nprint(sum(lst))",
        "tests": ["1 2 3\n", "5\n", "1 -1 2\n"]},
    6: {"title": "Append a Value", "difficulty": "Easy",
        "code": "lst = [int(x) for x in input().split()]\nx = int(input())\nlst.append(x)\nprint(lst)",
        "tests": ["1 2 3\n9\n", "5\n0\n", "1 2\n3\n"]},
    7: {"title": "Insert at the Front", "difficulty": "Easy",
        "code": "lst = [int(x) for x in input().split()]\nx = int(input())\nlst.insert(0, x)\nprint(lst)",
        "tests": ["2 3 4\n1\n", "5\n0\n", "1 2\n9\n"]},
    8: {"title": "Pop the Last Element", "difficulty": "Easy",
        "code": "lst = [int(x) for x in input().split()]\nremoved = lst.pop()\nprint(removed)\nprint(lst)",
        "tests": ["1 2 3\n", "7 8\n", "5 6 7 8\n"]},
    9: {"title": "Remove by Value", "difficulty": "Medium",
        "code": "lst = [int(x) for x in input().split()]\nx = int(input())\nlst.remove(x)\nprint(lst)",
        "tests": ["1 2 3 2\n2\n", "1 2 3\n3\n", "5 5 5\n5\n"]},
    10: {"title": "Sort Ascending", "difficulty": "Easy",
        "code": "lst = [int(x) for x in input().split()]\nlst.sort()\nprint(lst)",
        "tests": ["3 1 2\n", "1\n", "9 3 7 1\n"]},
    11: {"title": "Sort Descending", "difficulty": "Easy",
        "code": "lst = [int(x) for x in input().split()]\nlst.sort(reverse=True)\nprint(lst)",
        "tests": ["1 3 2\n", "1\n", "9 3 7 1\n"]},
    12: {"title": "Reverse a List", "difficulty": "Easy",
        "code": "lst = [int(x) for x in input().split()]\nlst.reverse()\nprint(lst)",
        "tests": ["1 2 3\n", "1\n", "9 7 5\n"]},
    13: {"title": "Slice a List", "difficulty": "Easy",
        "code": "lst = [int(x) for x in input().split()]\nprint(lst[1:3])",
        "tests": ["10 20 30 40\n", "1 2 3 4\n", "5 6 7 8\n"]},
    14: {"title": "Loop Over a List", "difficulty": "Easy",
        "code": "lst = [int(x) for x in input().split()]\nfor x in lst:\n    print(x)",
        "tests": ["4 7 2\n", "1\n", "1 2 3\n"]},
    15: {"title": "Count Even Numbers", "difficulty": "Easy",
        "code": "lst = [int(x) for x in input().split()]\nprint(sum(1 for x in lst if x % 2 == 0))",
        "tests": ["1 2 3 4\n", "1 3 5\n", "2 4 6\n"]},
    16: {"title": "Largest Element", "difficulty": "Easy",
        "code": "lst = [int(x) for x in input().split()]\nprint(max(lst))",
        "tests": ["3 9 1 7\n", "5\n", "-3 -1 -5\n"]},
    17: {"title": "Second Largest", "difficulty": "Medium",
        "code": "lst = sorted(int(x) for x in input().split())\nprint(lst[-2])",
        "tests": ["3 9 1 7\n", "1 2\n", "9 8 7 6\n"]},
    18: {"title": "Index of a Value", "difficulty": "Medium",
        "code": "lst = [int(x) for x in input().split()]\nx = int(input())\nprint(lst.index(x) if x in lst else -1)",
        "tests": ["5 8 3 9\n3\n", "1 2 3\n9\n", "1 2 3\n1\n"]},
    19: {"title": "Check Membership", "difficulty": "Easy",
        "code": "lst = [int(x) for x in input().split()]\nx = int(input())\nif x in lst:\n    print(\"Found\")\nelse:\n    print(\"Not found\")",
        "tests": ["1 5 9\n5\n", "1 5 9\n3\n", "2 2\n2\n"]},
    20: {"title": "Count Occurrences", "difficulty": "Easy",
        "code": "lst = [int(x) for x in input().split()]\nx = int(input())\nprint(lst.count(x))",
        "tests": ["1 2 2 3 2\n2\n", "1 2 3\n9\n", "5 5 5\n5\n"]},
    21: {"title": "Elements at Even Indices", "difficulty": "Medium",
        "code": "lst = [int(x) for x in input().split()]\nfor i in range(len(lst)):\n    if i % 2 == 0:\n        print(lst[i])",
        "tests": ["10 20 30 40 50\n", "1\n", "1 2 3 4\n"]},
    22: {"title": "Remove All Occurrences", "difficulty": "Medium",
        "code": "lst = [int(x) for x in input().split()]\nx = int(input())\nprint([v for v in lst if v != x])",
        "tests": ["1 2 3 2 4\n2\n", "1 2 3\n9\n", "5 5 5\n5\n"]},
    23: {"title": "Remove Duplicates (keep order)", "difficulty": "Medium",
        "code": "lst = [int(x) for x in input().split()]\nresult = []\nfor x in lst:\n    if x not in result:\n        result.append(x)\nprint(result)",
        "tests": ["1 2 1 3 2\n", "1\n", "1 1 1\n"]},
    24: {"title": "List of Squares", "difficulty": "Medium",
        "code": "lst = [int(x) for x in input().split()]\nprint([x ** 2 for x in lst])",
        "tests": ["2 3 4\n", "1\n", "-3 0 5\n"]},
    25: {"title": "Sum of Even Elements", "difficulty": "Medium",
        "code": "lst = [int(x) for x in input().split()]\nprint(sum(x for x in lst if x % 2 == 0))",
        "tests": ["1 2 3 4 5 6\n", "1 3 5\n", "2 4 6\n"]},
    26: {"title": "Check If Sorted", "difficulty": "Medium",
        "code": "lst = [int(x) for x in input().split()]\nsorted_flag = all(lst[i] <= lst[i+1] for i in range(len(lst)-1))\nif sorted_flag:\n    print(\"Sorted\")\nelse:\n    print(\"Not sorted\")",
        "tests": ["1 2 2 3\n", "3 2 1\n", "1 2 3\n"]},
    27: {"title": "Swap First and Last", "difficulty": "Medium",
        "code": "lst = [int(x) for x in input().split()]\nlst[0], lst[-1] = lst[-1], lst[0]\nprint(lst)",
        "tests": ["1 2 3 4\n", "1 2\n", "9 8 7\n"]},
    28: {"title": "Shift Left by One", "difficulty": "Medium",
        "code": "lst = [int(x) for x in input().split()]\nprint(lst[1:] + [lst[0]])",
        "tests": ["1 2 3 4\n", "1 2\n", "5 6 7\n"]},
    29: {"title": "Elements Greater Than Their Neighbors", "difficulty": "Hard",
        "code": "lst = [int(x) for x in input().split()]\ncount = 0\nfor i in range(1, len(lst) - 1):\n    if lst[i] > lst[i-1] and lst[i] > lst[i+1]:\n        count += 1\nprint(count)",
        "tests": ["1 5 2 4 3\n", "3 2 1\n", "1 3 2 3 1\n"]},
    30: {"title": "Average of a List", "difficulty": "Medium",
        "code": "lst = [int(x) for x in input().split()]\nprint(f\"{sum(lst) / len(lst):.2f}\")",
        "tests": ["10 20 30 40\n", "5\n", "1 2 3\n"]},
}
