QUESTIONS = {
    1: {"title": "Create a Tuple", "difficulty": "Very Easy",
        "code": "t = (1, 2, 3)\nprint(t)", "tests": [""]},
    2: {"title": "Length of a Tuple", "difficulty": "Very Easy",
        "code": "t = tuple(input().split())\nprint(len(t))",
        "tests": ["1 2 3\n", "5\n", "1 2 3 4\n"]},
    3: {"title": "Index a Tuple", "difficulty": "Very Easy",
        "code": "t = tuple(input().split())\nprint(t[1])",
        "tests": ["10 20 30\n", "1 2 3\n", "5 6 7 8\n"]},
    4: {"title": "Last Element of a Tuple", "difficulty": "Very Easy",
        "code": "t = tuple(input().split())\nprint(t[-1])",
        "tests": ["10 20 30\n", "5\n", "5 6 7\n"]},
    5: {"title": "Sum of a Tuple", "difficulty": "Easy",
        "code": "t = tuple(int(x) for x in input().split())\nprint(sum(t))",
        "tests": ["1 2 3 4\n", "5\n", "1 -1 2\n"]},
    6: {"title": "Unpack a Two-Element Tuple", "difficulty": "Easy",
        "code": "t = (int(input()), int(input()))\na, b = t\nprint(a + b)",
        "tests": ["5\n7\n", "0\n0\n", "-3\n9\n"]},
    7: {"title": "Unpack a Three-Element Tuple", "difficulty": "Easy",
        "code": "t = (int(input()), int(input()), int(input()))\nx, y, z = t\nprint((x + y + z) / 3)",
        "tests": ["2\n4\n6\n", "0\n0\n0\n", "1\n2\n3\n"]},
    8: {"title": "Swap Using a Tuple", "difficulty": "Easy",
        "code": "a = int(input())\nb = int(input())\na, b = b, a\nprint(a)\nprint(b)",
        "tests": ["1\n2\n", "5\n9\n", "-3\n7\n"]},
    9: {"title": "Count an Element in a Tuple", "difficulty": "Easy",
        "code": "t = tuple(int(x) for x in input().split())\nx = int(input())\nprint(t.count(x))",
        "tests": ["1 2 2 3\n2\n", "1 2 3\n9\n", "5 5\n5\n"]},
    10: {"title": "Index of an Element in a Tuple", "difficulty": "Medium",
        "code": "t = tuple(int(x) for x in input().split())\nx = int(input())\nprint(t.index(x))",
        "tests": ["5 8 3 8\n8\n", "1 2 3\n2\n", "7 7\n7\n"]},
    11: {"title": "Tuple From a List", "difficulty": "Easy",
        "code": "lst = [int(x) for x in input().split()]\nprint(tuple(lst))",
        "tests": ["1 2 3\n", "5\n", "1 1 1\n"]},
    12: {"title": "First and Last of a Tuple", "difficulty": "Easy",
        "code": "t = tuple(int(x) for x in input().split())\nprint(t[0])\nprint(t[-1])",
        "tests": ["3 7 2 9\n", "1 2\n", "5 6 7\n"]},
    13: {"title": "Slice a Tuple", "difficulty": "Easy",
        "code": "t = tuple(int(x) for x in input().split())\nprint(t[1:3])",
        "tests": ["10 20 30 40\n", "1 2 3 4\n", "5 6 7 8\n"]},
    14: {"title": "Tuple of a Number's Digits", "difficulty": "Medium",
        "code": "n = int(input())\nprint(tuple(int(c) for c in str(n)))",
        "tests": ["456\n", "1\n", "12345\n"]},
    15: {"title": "Immutability Awareness", "difficulty": "Medium",
        "code": "t = tuple(input().split())\nprint(type(t))",
        "tests": ["1 2 3\n", "5\n", "a b c\n"]},
    16: {"title": "Tuple Unpacking From a Function-Like Assign", "difficulty": "Medium",
        "code": "a, b = input().split(\",\")\nprint(int(a) + int(b))",
        "tests": ["3,7\n", "0,0\n", "10,20\n"]},
    17: {"title": "Nested Tuple Access", "difficulty": "Medium",
        "code": "t = (1, (2, 3), 4)\nprint(t[1][1])", "tests": [""]},
    18: {"title": "Tuple of Squares", "difficulty": "Medium",
        "code": "lst = [int(x) for x in input().split()]\nprint(tuple(x ** 2 for x in lst))",
        "tests": ["2 3 4\n", "1\n", "-3 0 5\n"]},
    19: {"title": "Count Even Elements in a Tuple", "difficulty": "Medium",
        "code": "t = tuple(int(x) for x in input().split())\nprint(sum(1 for x in t if x % 2 == 0))",
        "tests": ["1 2 3 4 5 6\n", "1 3 5\n", "2 4 6\n"]},
    20: {"title": "Unpack With Underscore", "difficulty": "Medium",
        "code": "a = int(input())\n_ = int(input())\nc = int(input())\nprint(a + c)",
        "tests": ["1\n2\n3\n", "5\n9\n7\n", "0\n0\n0\n"]},
    21: {"title": "Check If a Tuple Is a Palindrome", "difficulty": "Medium",
        "code": "t = tuple(int(x) for x in input().split())\nif t == t[::-1]:\n    print(\"Palindrome\")\nelse:\n    print(\"Not palindrome\")",
        "tests": ["1 2 2 1\n", "1 2 3\n", "5 5\n"]},
    22: {"title": "First Element of Each of Several Tuples", "difficulty": "Medium",
        "code": "n = int(input())\nfor _ in range(n):\n    a, b = map(int, input().split())\n    t = (a, b)\n    print(t[0])",
        "tests": ["2\n1 9\n2 8\n", "1\n5 5\n", "3\n1 2\n3 4\n5 6\n"]},
    23: {"title": "Tuple of Word Lengths", "difficulty": "Medium",
        "code": "s = input()\nprint(tuple(len(w) for w in s.split()))",
        "tests": ["hi there\n", "hello\n", "a bb ccc\n"]},
    24: {"title": "Maximum and Minimum of a Tuple", "difficulty": "Medium",
        "code": "t = tuple(int(x) for x in input().split())\nprint(max(t))\nprint(min(t))",
        "tests": ["3 9 1 7\n", "5\n", "-3 0 5\n"]},
    25: {"title": "Concatenate Two Tuples", "difficulty": "Medium",
        "code": "t1 = tuple(int(x) for x in input().split())\nt2 = tuple(int(x) for x in input().split())\nprint(t1 + t2)",
        "tests": ["1 2\n3 4\n", "5\n6\n", "1 2 3\n4 5\n"]},
    26: {"title": "Sum of First and Last of a Tuple", "difficulty": "Easy",
        "code": "t = tuple(int(x) for x in input().split())\nprint(t[0] + t[-1])",
        "tests": ["3 5 7 2\n", "1 2\n", "-3 5 10\n"]},
    27: {"title": "Tuple of Multiples", "difficulty": "Medium",
        "code": "k = int(input())\nn = int(input())\nprint(tuple(i * k for i in range(1, n + 1)))",
        "tests": ["5\n3\n", "2\n4\n", "7\n1\n"]},
    28: {"title": "Check If a Value Is in a Tuple", "difficulty": "Easy",
        "code": "t = tuple(int(x) for x in input().split())\nx = int(input())\nif x in t:\n    print(\"Present\")\nelse:\n    print(\"Absent\")",
        "tests": ["1 5 9\n5\n", "1 5 9\n3\n", "2 2\n2\n"]},
    29: {"title": "Unpack Nested Pairs", "difficulty": "Hard",
        "code": "n = int(input())\nfor _ in range(n):\n    a, b = map(int, input().split())\n    t = (a, b)\n    print(t[1])",
        "tests": ["2\n1 9\n2 8\n", "1\n5 5\n", "3\n1 2\n3 4\n5 6\n"]},
    30: {"title": "Tuple of Elements at Even Indices", "difficulty": "Medium",
        "code": "t = tuple(int(x) for x in input().split())\nprint(t[::2])",
        "tests": ["10 20 30 40 50\n", "1\n", "1 2 3 4\n"]},
}
