QUESTIONS = {
    1: {"title": "Create a Set", "difficulty": "Very Easy",
        "code": "s = {1, 2, 3}\nprint(s)", "tests": [""]},
    2: {"title": "Length of a Set", "difficulty": "Very Easy",
        "code": "lst = [int(x) for x in input().split()]\nprint(len(set(lst)))",
        "tests": ["1 2 2 3\n", "1 1 1\n", "1 2 3\n"]},
    3: {"title": "Add a Value to a Set", "difficulty": "Easy",
        "code": "s = set(int(x) for x in input().split())\nx = int(input())\ns.add(x)\nprint(s)",
        "tests": ["1 2 3\n9\n", "1 2\n1\n", "5 5\n9\n"]},
    4: {"title": "Remove a Value From a Set", "difficulty": "Easy",
        "code": "s = set(int(x) for x in input().split())\nx = int(input())\ns.discard(x)\nprint(s)",
        "tests": ["1 2 3 4\n3\n", "1 2\n2\n", "5 6 7\n5\n"]},
    5: {"title": "Union of Two Sets", "difficulty": "Easy",
        "code": "A = set(int(x) for x in input().split())\nB = set(int(x) for x in input().split())\nprint(A | B)",
        "tests": ["1 2 3\n3 4 5\n", "1 2\n3 4\n", "1\n1\n"]},
    6: {"title": "Intersection of Two Sets", "difficulty": "Easy",
        "code": "A = set(int(x) for x in input().split())\nB = set(int(x) for x in input().split())\nprint(A & B)",
        "tests": ["1 2 3 4\n3 4 5\n", "1 2\n3 4\n", "1 2\n1 2\n"]},
    7: {"title": "Difference of Two Sets", "difficulty": "Easy",
        "code": "A = set(int(x) for x in input().split())\nB = set(int(x) for x in input().split())\nprint(A - B)",
        "tests": ["1 2 3 4\n2 4\n", "1 2\n1 2\n", "5 6\n1\n"]},
    8: {"title": "Remove Duplicates From a List", "difficulty": "Easy",
        "code": "lst = [int(x) for x in input().split()]\nprint(list(set(lst)))",
        "tests": ["3 1 3 2 1\n", "1 1 1\n", "5 5 6\n"]},
    9: {"title": "Count Unique Characters", "difficulty": "Easy",
        "code": "s = input()\nprint(len(set(s)))",
        "tests": ["banana\n", "abc\n", "aaaa\n"]},
    10: {"title": "Check Membership", "difficulty": "Easy",
        "code": "s = set(int(x) for x in input().split())\nx = int(input())\nif x in s:\n    print(\"Present\")\nelse:\n    print(\"Absent\")",
        "tests": ["1 5 9\n5\n", "1 5 9\n3\n", "2 2\n2\n"]},
    11: {"title": "Symmetric Difference", "difficulty": "Medium",
        "code": "A = set(int(x) for x in input().split())\nB = set(int(x) for x in input().split())\nprint(A ^ B)",
        "tests": ["1 2 3\n3 4 5\n", "1 2\n1 2\n", "1\n2\n"]},
    12: {"title": "Check Subset", "difficulty": "Medium",
        "code": "A = set(int(x) for x in input().split())\nB = set(int(x) for x in input().split())\nif A <= B:\n    print(\"Subset\")\nelse:\n    print(\"Not subset\")",
        "tests": ["1 2\n1 2 3 4\n", "1 2\n2 3\n", "1\n1\n"]},
    13: {"title": "Check Superset", "difficulty": "Medium",
        "code": "A = set(int(x) for x in input().split())\nB = set(int(x) for x in input().split())\nif A >= B:\n    print(\"Superset\")\nelse:\n    print(\"Not superset\")",
        "tests": ["1 2 3 4\n2 4\n", "1 2\n3\n", "1 2\n1 2\n"]},
    14: {"title": "Sum of Unique Values", "difficulty": "Medium",
        "code": "lst = [int(x) for x in input().split()]\nprint(sum(set(lst)))",
        "tests": ["1 2 2 3 4 4\n", "1 1 1\n", "1 2 3\n"]},
    15: {"title": "Check Disjoint", "difficulty": "Medium",
        "code": "A = set(int(x) for x in input().split())\nB = set(int(x) for x in input().split())\nif not (A & B):\n    print(\"Disjoint\")\nelse:\n    print(\"Not disjoint\")",
        "tests": ["1 2 3\n4 5 6\n", "1 2\n2 3\n", "1\n1\n"]},
    16: {"title": "Count Distinct Digits", "difficulty": "Medium",
        "code": "n = int(input())\nprint(len(set(str(n))))",
        "tests": ["112233\n", "1\n", "12345\n"]},
    17: {"title": "Common Elements Count", "difficulty": "Medium",
        "code": "A = set(int(x) for x in input().split())\nB = set(int(x) for x in input().split())\nprint(len(A & B))",
        "tests": ["1 2 3 4\n3 4 5\n", "1 2\n3 4\n", "1 2\n1 2\n"]},
    18: {"title": "Union Size", "difficulty": "Medium",
        "code": "A = set(int(x) for x in input().split())\nB = set(int(x) for x in input().split())\nprint(len(A | B))",
        "tests": ["1 2 3\n3 4\n", "1\n1\n", "1 2\n3 4\n"]},
    19: {"title": "Only in A (size of A - B)", "difficulty": "Medium",
        "code": "A = set(int(x) for x in input().split())\nB = set(int(x) for x in input().split())\nprint(len(A - B))",
        "tests": ["1 2 3 4 5\n2 4\n", "1 2\n1 2\n", "5 6\n1\n"]},
    20: {"title": "Common Values as a Sorted List", "difficulty": "Medium",
        "code": "A = set(int(x) for x in input().split())\nB = set(int(x) for x in input().split())\nprint(sorted(A & B))",
        "tests": ["4 1 3 2\n5 3 4 6\n", "1 2\n3 4\n", "1 2\n1 2\n"]},
    21: {"title": "Check for Duplicates", "difficulty": "Easy",
        "code": "lst = [int(x) for x in input().split()]\nif len(lst) > len(set(lst)):\n    print(\"Duplicate\")\nelse:\n    print(\"Unique\")",
        "tests": ["1 2 3 2\n", "1 2 3\n", "5 5\n"]},
    22: {"title": "Unique Vowels", "difficulty": "Medium",
        "code": "s = input().lower()\nprint(len(set(s) & set(\"aeiou\")))",
        "tests": ["beautiful\n", "hello\n", "xyz\n"]},
    23: {"title": "Elements in A or B but Not in C", "difficulty": "Hard",
        "code": "A = set(int(x) for x in input().split())\nB = set(int(x) for x in input().split())\nC = set(int(x) for x in input().split())\nprint((A | B) - C)",
        "tests": ["1 2 3\n3 4 5\n4 5 6\n", "1 2\n3\n4\n", "1\n2\n1\n"]},
    24: {"title": "Intersection of Three Sets", "difficulty": "Medium",
        "code": "A = set(int(x) for x in input().split())\nB = set(int(x) for x in input().split())\nC = set(int(x) for x in input().split())\nprint(A & B & C)",
        "tests": ["1 2 3 4\n2 3 4 5\n3 4 5 6\n", "1 2\n1 2\n1 2\n", "1 2\n3 4\n5 6\n"]},
    25: {"title": "Unique Words in a Sentence", "difficulty": "Medium",
        "code": "s = input()\nprint(len(set(s.split())))",
        "tests": ["the cat and the dog\n", "hi\n", "a a b\n"]},
    26: {"title": "Symmetric Difference Size", "difficulty": "Medium",
        "code": "A = set(int(x) for x in input().split())\nB = set(int(x) for x in input().split())\nprint(len(A ^ B))",
        "tests": ["1 2 3\n3 4 5\n", "1 2\n1 2\n", "1\n2\n"]},
    27: {"title": "Second Largest Distinct Value", "difficulty": "Medium",
        "code": "lst = [int(x) for x in input().split()]\nprint(sorted(set(lst))[-2])",
        "tests": ["7 3 9 1 9\n", "1 2\n", "5 5 4 3\n"]},
    28: {"title": "Max of a Set", "difficulty": "Easy",
        "code": "lst = [int(x) for x in input().split()]\nprint(max(set(lst)))",
        "tests": ["4 9 2 9 7\n", "1\n", "-3 -1 -5\n"]},
    29: {"title": "Check If All Values Are Even", "difficulty": "Medium",
        "code": "s = set(int(x) for x in input().split())\nif all(x % 2 == 0 for x in s):\n    print(\"All even\")\nelse:\n    print(\"Not all even\")",
        "tests": ["2 4 6\n", "2 3\n", "0 2\n"]},
    30: {"title": "Set of First Letters", "difficulty": "Medium",
        "code": "s = input()\nprint(set(w[0] for w in s.split()))",
        "tests": ["apple banana cherry\n", "a b c\n", "hello\n"]},
}
