QUESTIONS = {
    1: {"title": "Define and Call a Function", "difficulty": "Very Easy",
        "code": 'def say_hello():\n    print("Hello!")\nsay_hello()', "tests": [""]},
    2: {"title": "Function With a Parameter", "difficulty": "Very Easy",
        "code": 'def greet(name):\n    print(f"Hello, {name}!")\ngreet(input())',
        "tests": ["Aman\n", "Zara\n", "Bob\n"]},
    3: {"title": "Function With a Return", "difficulty": "Very Easy",
        "code": "def add(a, b):\n    return a + b\na = int(input())\nb = int(input())\nprint(add(a, b))",
        "tests": ["5\n7\n", "0\n0\n", "-3\n9\n"]},
    4: {"title": "Call a Function With Two Arguments", "difficulty": "Very Easy",
        "code": "def multiply(a, b):\n    return a * b\na = int(input())\nb = int(input())\nprint(multiply(a, b))",
        "tests": ["6\n7\n", "0\n5\n", "-4\n3\n"]},
    5: {"title": "Default Parameter", "difficulty": "Easy",
        "code": "def power(x, e=2):\n    return x ** e\nn = int(input())\nprint(power(n))",
        "tests": ["7\n", "0\n", "5\n"]},
    6: {"title": "Override a Default Parameter", "difficulty": "Easy",
        "code": "def power(x, e=2):\n    return x ** e\nx = int(input())\ne = int(input())\nprint(power(x, e))",
        "tests": ["2\n10\n", "5\n3\n", "1\n5\n"]},
    7: {"title": "Keyword Arguments", "difficulty": "Easy",
        "code": "def divide(dividend, divisor):\n    return dividend / divisor\na = int(input())\nb = int(input())\nprint(divide(dividend=a, divisor=b))",
        "tests": ["10\n2\n", "7\n2\n", "1\n4\n"]},
    8: {"title": "Function Using *args", "difficulty": "Medium",
        "code": "def total(*args):\n    return sum(args)\nn = int(input())\nvalues = [int(input()) for _ in range(n)]\nprint(total(*values))",
        "tests": ["3\n1\n2\n3\n", "1\n5\n", "2\n-3\n4\n"]},
    9: {"title": "Function Using **kwargs", "difficulty": "Medium",
        "code": "def show(**kwargs):\n    for k, v in kwargs.items():\n        print(f\"{k}={v}\")\nshow(a=1, b=2)",
        "tests": [""]},
    10: {"title": "Function Returning a Boolean", "difficulty": "Easy",
        "code": "def is_even(n):\n    return n % 2 == 0\nn = int(input())\nprint(is_even(n))",
        "tests": ["8\n", "7\n", "0\n"]},
    11: {"title": "Function With a Conditional Return", "difficulty": "Easy",
        "code": "def larger(a, b):\n    if a > b:\n        return a\n    else:\n        return b\na = int(input())\nb = int(input())\nprint(larger(a, b))",
        "tests": ["7\n3\n", "3\n7\n", "5\n5\n"]},
    12: {"title": "Scope: Local Variable", "difficulty": "Medium",
        "code": "def f():\n    x = 5\n    return x\nprint(f())", "tests": [""]},
    13: {"title": "Scope: Function Can't See a Local Outside", "difficulty": "Medium",
        "code": "def f():\n    y = 10\n    return y\nprint(f())", "tests": [""]},
    14: {"title": "Function Returning Multiple Values", "difficulty": "Medium",
        "code": "def min_max(a, b):\n    return (min(a, b), max(a, b))\na = int(input())\nb = int(input())\nlo, hi = min_max(a, b)\nprint(lo)\nprint(hi)",
        "tests": ["3\n7\n", "7\n3\n", "5\n5\n"]},
    15: {"title": "Lambda for Addition", "difficulty": "Easy",
        "code": "add = lambda a, b: a + b\na = int(input())\nb = int(input())\nprint(add(a, b))",
        "tests": ["4\n9\n", "0\n0\n", "-3\n7\n"]},
    16: {"title": "Lambda for a Square", "difficulty": "Easy",
        "code": "square = lambda x: x * x\nn = int(input())\nprint(square(n))",
        "tests": ["6\n", "0\n", "-4\n"]},
    17: {"title": "Function Computing a Factorial", "difficulty": "Medium",
        "code": "def factorial(n):\n    p = 1\n    for i in range(1, n + 1):\n        p *= i\n    return p\nn = int(input())\nprint(factorial(n))",
        "tests": ["5\n", "0\n", "10\n"]},
    18: {"title": "Function Returning a List", "difficulty": "Medium",
        "code": "def first_evens(n):\n    return [i * 2 for i in range(1, n + 1)]\nn = int(input())\nprint(first_evens(n))",
        "tests": ["4\n", "1\n", "6\n"]},
    19: {"title": "Function Returning a String", "difficulty": "Easy",
        "code": "def reverse_str(s):\n    return s[::-1]\ns = input()\nprint(reverse_str(s))",
        "tests": ["hello\n", "a\n", "python\n"]},
    20: {"title": "Function With a List Argument", "difficulty": "Medium",
        "code": "def sum_list(lst):\n    return sum(lst)\nlst = [int(x) for x in input().split()]\nprint(sum_list(lst))",
        "tests": ["1 2 3\n", "5\n", "1 -1 2\n"]},
    21: {"title": "Function Counting Evens in a List", "difficulty": "Medium",
        "code": "def count_even(lst):\n    return sum(1 for x in lst if x % 2 == 0)\nlst = [int(x) for x in input().split()]\nprint(count_even(lst))",
        "tests": ["1 2 3 4 5 6\n", "1 3 5\n", "2 4 6\n"]},
    22: {"title": "Default Parameter in a Calculation", "difficulty": "Medium",
        "code": "def apply_discount(price, discount=10):\n    return price * (100 - discount) / 100\nprice = int(input())\ndiscount = int(input())\nprint(apply_discount(price, discount))",
        "tests": ["1000\n20\n", "100\n0\n", "500\n10\n"]},
    23: {"title": "Keyword Arguments With a Function", "difficulty": "Medium",
        "code": 'def describe(name, age):\n    return f"{name} is {age} years old"\nname = input()\nage = int(input())\nprint(describe(name=name, age=age))',
        "tests": ["Aman\n25\n", "Bob\n1\n", "Zara\n40\n"]},
    24: {"title": "Function Using *args for Maximum", "difficulty": "Medium",
        "code": "def my_max(*args):\n    return max(args)\nn = int(input())\nvalues = [int(input()) for _ in range(n)]\nprint(my_max(*values))",
        "tests": ["3\n5\n9\n2\n", "1\n7\n", "4\n-1\n-2\n-3\n-4\n"]},
    25: {"title": "Function Returning a Dictionary", "difficulty": "Medium",
        "code": "def make_dict(k, v):\n    return {k: v}\nk = input()\nv = int(input())\nprint(make_dict(k, v))",
        "tests": ["apple\n5\n", "pen\n1\n", "x\n9\n"]},
    26: {"title": "Global Variable Scope (read)", "difficulty": "Medium",
        "code": "rate = 5\ndef calc(value):\n    return rate * value\nn = int(input())\nprint(calc(n))",
        "tests": ["3\n", "0\n", "10\n"]},
    27: {"title": "Lambda With a List (map-style)", "difficulty": "Medium",
        "code": "double = lambda x: 2 * x\nlst = [int(x) for x in input().split()]\nprint([double(x) for x in lst])",
        "tests": ["1 2 3\n", "5\n", "-1 0 1\n"]},
    28: {"title": "Function With Both *args and **kwargs", "difficulty": "Hard",
        "code": "def stats(*args, mode=\"sum\"):\n    if mode == \"sum\":\n        return sum(args)\n    else:\n        return len(args)\nn = int(input())\nvalues = [int(input()) for _ in range(n)]\nmode = input()\nprint(stats(*values, mode=mode))",
        "tests": ["3\n5\n5\n9\ncount\n", "2\n1\n2\nsum\n", "4\n7\n7\n7\n7\ncount\n"]},
    29: {"title": "Nested Function (inner helper)", "difficulty": "Hard",
        "code": "def outer():\n    def inner(x):\n        return x * 3\n    return inner(3)\nprint(outer())", "tests": [""]},
    30: {"title": "Function Calling Another Function", "difficulty": "Hard",
        "code": "def square(x):\n    return x * x\ndef sum_of_squares(a, b):\n    return square(a) + square(b)\na = int(input())\nb = int(input())\nprint(sum_of_squares(a, b))",
        "tests": ["3\n4\n", "0\n0\n", "5\n12\n"]},
}
